-- =========================
-- SUPCONTENT - init.sql
-- PostgreSQL schema
-- =========================

SET client_min_messages TO WARNING;

-- =========================
-- TABLES
-- =========================

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(100) NOT NULL UNIQUE CHECK (length(username) >= 3),
  password_hash VARCHAR(255),
  avatar_url VARCHAR(500),
  bio TEXT,
  website_url VARCHAR(500),
  theme_preference VARCHAR(20) NOT NULL DEFAULT 'light',
  language_preference VARCHAR(20) NOT NULL DEFAULT 'en',
  is_banned BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE oauth_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  provider VARCHAR(50) NOT NULL,
  provider_user_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id VARCHAR(100) NOT NULL,
  source_api VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  overview TEXT,
  poster_url VARCHAR(500),
  release_date DATE,
  runtime_minutes INT,
  cached_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE movie_categories (
  movie_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  PRIMARY KEY (movie_id, category_id)
);

CREATE TABLE user_library (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  movie_id BIGINT NOT NULL,
  status VARCHAR(30) NOT NULL CHECK (status IN ('TO_WATCH', 'IN_PROGRESS', 'COMPLETED', 'DROPPED')),
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  last_interaction_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE custom_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE custom_list_movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id BIGINT NOT NULL,
  movie_id BIGINT NOT NULL,
  added_at TIMESTAMP NOT NULL DEFAULT NOW(),
  position INT
);

CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  movie_id BIGINT NOT NULL,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  text TEXT,
  contains_spoiler BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP
);

CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  parent_comment_id BIGINT,
  text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP
);

CREATE TABLE review_likes (
  user_id BIGINT NOT NULL,
  review_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, review_id)
);

CREATE TABLE follows (
  follower_id BIGINT NOT NULL,
  followed_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (follower_id, followed_id),
  CHECK (follower_id <> followed_id)
);

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  actor_user_id BIGINT,
  type VARCHAR(50) NOT NULL,
  entity_type VARCHAR(50),
  entity_id BIGINT,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT NOT NULL,
  receiver_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_user_id BIGINT NOT NULL,
  target_type VARCHAR(50) NOT NULL CHECK (target_type IN ('REVIEW', 'COMMENT', 'USER')),
  target_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  handled_by BIGINT,
  handled_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- =========================
-- UNIQUE INDEXES
-- =========================

CREATE UNIQUE INDEX ux_oauth_accounts_provider_user
  ON oauth_accounts (provider, provider_user_id);

CREATE UNIQUE INDEX ux_movies_source_external
  ON movies (source_api, external_id);

CREATE UNIQUE INDEX ux_user_library_user_movie
  ON user_library (user_id, movie_id);

CREATE UNIQUE INDEX ux_custom_list_movies_list_movie
  ON custom_list_movies (list_id, movie_id);

CREATE UNIQUE INDEX ux_reviews_user_movie
  ON reviews (user_id, movie_id);

-- =========================
-- PERFORMANCE INDEXES
-- =========================

CREATE INDEX idx_reviews_movie_id
  ON reviews (movie_id);

CREATE INDEX idx_reviews_user_id
  ON reviews (user_id);

CREATE INDEX idx_comments_review_id
  ON comments (review_id);

CREATE INDEX idx_notifications_user_id
  ON notifications (user_id);

CREATE INDEX idx_notifications_unread
  ON notifications (user_id, is_read);

CREATE INDEX idx_user_library_user_id
  ON user_library (user_id);

CREATE INDEX idx_follows_followed_id
  ON follows (followed_id);

CREATE INDEX idx_messages_receiver_id
  ON messages (receiver_id);

CREATE INDEX idx_custom_lists_user_id
  ON custom_lists (user_id);

-- =========================
-- FOREIGN KEYS
-- =========================

ALTER TABLE user_roles
  ADD CONSTRAINT fk_user_roles_user
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE user_roles
  ADD CONSTRAINT fk_user_roles_role
  FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE;

ALTER TABLE oauth_accounts
  ADD CONSTRAINT fk_oauth_accounts_user
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE movie_categories
  ADD CONSTRAINT fk_movie_categories_movie
  FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE;

ALTER TABLE movie_categories
  ADD CONSTRAINT fk_movie_categories_category
  FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE;

ALTER TABLE user_library
  ADD CONSTRAINT fk_user_library_user
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE user_library
  ADD CONSTRAINT fk_user_library_movie
  FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE;

ALTER TABLE custom_lists
  ADD CONSTRAINT fk_custom_lists_user
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE custom_list_movies
  ADD CONSTRAINT fk_custom_list_movies_list
  FOREIGN KEY (list_id) REFERENCES custom_lists (id) ON DELETE CASCADE;

ALTER TABLE custom_list_movies
  ADD CONSTRAINT fk_custom_list_movies_movie
  FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE;

ALTER TABLE reviews
  ADD CONSTRAINT fk_reviews_user
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE reviews
  ADD CONSTRAINT fk_reviews_movie
  FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE;

ALTER TABLE comments
  ADD CONSTRAINT fk_comments_review
  FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE;

ALTER TABLE comments
  ADD CONSTRAINT fk_comments_user
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE comments
  ADD CONSTRAINT fk_comments_parent
  FOREIGN KEY (parent_comment_id) REFERENCES comments (id) ON DELETE CASCADE;

ALTER TABLE review_likes
  ADD CONSTRAINT fk_review_likes_user
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE review_likes
  ADD CONSTRAINT fk_review_likes_review
  FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE;

ALTER TABLE follows
  ADD CONSTRAINT fk_follows_follower
  FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE follows
  ADD CONSTRAINT fk_follows_followed
  FOREIGN KEY (followed_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE notifications
  ADD CONSTRAINT fk_notifications_user
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE notifications
  ADD CONSTRAINT fk_notifications_actor_user
  FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE messages
  ADD CONSTRAINT fk_messages_sender
  FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE messages
  ADD CONSTRAINT fk_messages_receiver
  FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE reports
  ADD CONSTRAINT fk_reports_reporter
  FOREIGN KEY (reporter_user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE reports
  ADD CONSTRAINT fk_reports_handled_by
  FOREIGN KEY (handled_by) REFERENCES users (id) ON DELETE SET NULL;

-- =========================
-- SEED DATA
-- =========================

INSERT INTO roles (name) VALUES ('USER')
ON CONFLICT (name) DO NOTHING;

INSERT INTO roles (name) VALUES ('ADMIN')
ON CONFLICT (name) DO NOTHING;