SET client_min_messages TO WARNING;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================
-- TABLES
-- =========================

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(100) NOT NULL UNIQUE CHECK (length(username) >= 3),
  password_hash VARCHAR(255),
  avatar_url VARCHAR(500),
  bio TEXT,
  website_url VARCHAR(500),
  theme_preference VARCHAR(20) NOT NULL DEFAULT 'light',
  language_preference VARCHAR(20) NOT NULL DEFAULT 'en',
  is_banned BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
  user_id UUID NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE oauth_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  provider VARCHAR(50) NOT NULL,
  provider_user_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id VARCHAR(100) NOT NULL,
  source_api VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  overview TEXT,
  poster_url VARCHAR(500),
  release_date DATE,
  runtime_minutes INT,
  cached_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE movie_categories (
  movie_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  PRIMARY KEY (movie_id, category_id)
);

CREATE TABLE user_library (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  movie_id BIGINT NOT NULL,
  status VARCHAR(30) NOT NULL CHECK (status IN ('TO_WATCH', 'IN_PROGRESS', 'COMPLETED', 'DROPPED')),
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  last_interaction_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE custom_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE custom_list_movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id BIGINT NOT NULL,
  movie_id BIGINT NOT NULL,
  added_at TIMESTAMP NOT NULL DEFAULT NOW(),
  position INT
);

CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  movie_id BIGINT NOT NULL,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  text TEXT,
  contains_spoiler BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP
);

CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT NOT NULL,
  user_id UUID NOT NULL,
  parent_comment_id BIGINT,
  text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP
);

CREATE TABLE review_likes (
  user_id UUID NOT NULL,
  review_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, review_id)
);

CREATE TABLE follows (
  follower_id UUID NOT NULL,
  followed_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (follower_id, followed_id),
  CHECK (follower_id <> followed_id)
);

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  actor_user_id UUID,
  type VARCHAR(50) NOT NULL,
  entity_type VARCHAR(50),
  entity_id BIGINT,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID NOT NULL,
  receiver_id UUID NOT NULL,
  content TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_user_id UUID NOT NULL,
  target_type VARCHAR(50) NOT NULL CHECK (target_type IN ('REVIEW', 'COMMENT', 'USER')),
  target_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  handled_by UUID,
  handled_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- =========================
-- INDEXES
-- =========================

CREATE UNIQUE INDEX ux_oauth_accounts_provider_user
  ON oauth_accounts (provider, provider_user_id);

CREATE UNIQUE INDEX ux_movies_source_external
  ON movies (source_api, external_id);

CREATE UNIQUE INDEX ux_user_library_user_movie
  ON user_library (user_id, movie_id);

CREATE UNIQUE INDEX ux_custom_list_movies_list_movie
  ON custom_list_movies (list_id, movie_id);

CREATE UNIQUE INDEX ux_reviews_user_movie
  ON reviews (user_id, movie_id);

-- =========================
-- FOREIGN KEYS
-- =========================

ALTER TABLE user_roles
  ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE user_roles
  ADD FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE;

ALTER TABLE oauth_accounts
  ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE movie_categories
  ADD FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE;

ALTER TABLE movie_categories
  ADD FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE;

ALTER TABLE user_library
  ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE user_library
  ADD FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE;

ALTER TABLE custom_lists
  ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE custom_list_movies
  ADD FOREIGN KEY (list_id) REFERENCES custom_lists (id) ON DELETE CASCADE;

ALTER TABLE custom_list_movies
  ADD FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE;

ALTER TABLE reviews
  ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE reviews
  ADD FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE;

ALTER TABLE comments
  ADD FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE;

ALTER TABLE comments
  ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE comments
  ADD FOREIGN KEY (parent_comment_id) REFERENCES comments (id) ON DELETE CASCADE;

ALTER TABLE review_likes
  ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE review_likes
  ADD FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE;

ALTER TABLE follows
  ADD FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE follows
  ADD FOREIGN KEY (followed_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE notifications
  ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE notifications
  ADD FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE messages
  ADD FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE messages
  ADD FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE reports
  ADD FOREIGN KEY (reporter_user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE reports
  ADD FOREIGN KEY (handled_by) REFERENCES users (id) ON DELETE SET NULL;

-- =========================
-- SEED
-- =========================

INSERT INTO roles (name) VALUES ('USER')
ON CONFLICT DO NOTHING;

INSERT INTO roles (name) VALUES ('ADMIN')
ON CONFLICT DO NOTHING;